version: '3.3'

services:
  ui:
    volumes:
      - ui:/app
    command: puma --debug -w 2

  comment:
    volumes:
      - comment:/app

  post:
    volumes:
      - post-py:/app

volumes:
  ui:
  comment:
  post-py:
